apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - image: mysql:8.0
        name: {{.Values.name}}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: {{.Values.mysqlPWD}}
        ports:
        - containerPort: {{.Values.serviceTargetPort}}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
